apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: qsan-xevo-storage
provisioner: xevo.csi.qsan.com
parameters:
  protocol: iscsi
  server: 192.168.201.85
  pool: Pool_Johnson
  iscsiPortals: 192.168.201.201,192.168.201.202,192.168.201.200
  target: HostGroup_Johnson
allowVolumeExpansion: true
